version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(levelname)s - %(asctime)s - %(name)s - %(message)s'
    datefmt: '%d.%m.%Y %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    filename: logs/dbInteract.log
loggers:
  "":
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console,file]
  propagate: no
